angular
    .module('clientIO')
    .factory('UnitListFactory', UnitListFactoryCtrl);


function UnitListFactoryCtrl() {

        fontList =

            [
                    'Arial',
                    'Helvetica',
                    'Times New Roman',
                    'Courier New',
                    'Georgia', 'Garamond',
                    'Tahoma',
                    'Lucida Console',
                    'Comic Sans MS'
            ];

        selectType = ['Meters'];

        typeSort =

            [
                    'Al',
                    'Electricity',
                    'Gas',
                    'Water',
                    'Fluid Energy',
                    'Waste',
                    'Diesel'
            ];

        objectTypes =

            [
                    'Binary Input',
                    'Binary Output',
                    'Binary Value'

            ];

        PropertyList =

            [
                    'Present Value',
                    'Priority Array',
                    'Relinquish Default'

            ];






        engineeringUnitList =

            [
                    "Square Meters",
                    "Square Feet",
                    "Milliamperes",
                    "Amperes",
                    "Ohms",
                    "Volts",
                    "Kilovolts",
                    "Megavolts",
                    "VoltAmperes",
                    "Kilovolt Amperes",
                    "Megavolt Amperes",
                    "VoltAmperes Reactive",
                    "Kilovolt Amperes Reactive",
                    "Megavolt Amperes Reactive",
                    "Degrees Phase",
                    "Power Factor",
                    "Joules",
                    "Kilojoules",
                    "WattHours",
                    "Kilowatt Hours",
                    "BTUs",
                    "Therms",
                    "Ton Hours",
                    "Joules Per Kilogram Dry Air",
                    "Btus Per Pound Dry Air",
                    "Cycles Per Hour",
                    "Cycles Per Minute",
                    "Hertz",
                    "Grams Of Water Per Kilogram Dry Air",
                    "Percent Relative Humidity",
                    "Millimeters",
                    "Meters",
                    "Inches",
                    "Feet",
                    "Watts Per Square Foot",
                    "Watts Per Square Meter",
                    "Lumens",
                    "Luxes",
                    "Foot Candles",
                    "Kilograms",
                    "Pounds Mass",
                    "Tons",
                    "Kilograms Per Second",
                    "Kilograms Per Minute",
                    "Kilograms Per Hour",
                    "Pounds Mass Per Minute",
                    "Pounds Mass Per Hour",
                    "Watts",
                    "Kilowatts",
                    "Megawatts",
                    "BTUs Per Hour",
                    "Horsepower",
                    "Tons Refrigeration",
                    "Pascals",
                    "Kilopascals",
                    "Bars",
                    "Pounds Force Per Square Inch",
                    "Centimeters Of Water",
                    "Inches Of Water",
                    "Millimeters Of Mercury",
                    "Centimeters Of Mercury",
                    "Inches Of Mercury",
                    "Degrees Celsius",
                    "Degrees Kelvin",
                    "Degrees Fahrenheit",
                    "Degree Days Celsius",
                    "Degree Days Fahrenheit",
                    "Years",
                    "Months",
                    "Weeks",
                    "Days",
                    "Hours",
                    "Minutes",
                    "Seconds",
                    "Meters Per Second",
                    "Kilometers Per Hour",
                    "Feet Per Second",
                    "Feet Per Minute",
                    "Miles Per Hour",
                    "Cubic Feet",
                    "Cubic Meters",
                    "Imperial Gallons",
                    "Liters",
                    "Us Gallons",
                    "Cubic Feet Per Minute",
                    "Cubic Meters Per Second",
                    "Imperial Gallons Per Minute",
                    "Liters Per Second",
                    "Liters Per Minute",
                    "Us Gallons Per Minute",
                    "Degrees Angular",
                    "Degrees Celsius Per Hour",
                    "Degrees Celsius Per Minute",
                    "Degrees Fahrenheit Per Hour",
                    "Degrees Fahrenheit Per Minute",
                    "NoUnits",
                    "Parts Per Million",
                    "Parts Per Billion",
                    "Percent",
                    "Percent Per Second",
                    "Per Minute",
                    "Per Second",
                    "Psi Per Degree Fahrenheit",
                    "Radians",
                    "Revolutions Per Minute",
                    "Currency 1",
                    "Currency 2",
                    "Currency 3",
                    "Currency 4",
                    "Currency 5",
                    "Currency 6",
                    "Currency 7",
                    "Currency 8",
                    "Currency 9",
                    "Currency 10",
                    "Square Inches",
                    "Square Centimeters",
                    "Btus Per Pound",
                    "Centimeters",
                    "Pounds Mass Per Second",
                    "Delta Degrees Fahrenheit",
                    "Delta Degrees Kelvin",
                    "Kilohms",
                    "Megohms",
                    "Millivolts",
                    "Kilojoules Per Kilogram",
                    "Megajoules",
                    "Joules Per Degree Kelvin",
                    "Joules Per Kilogram Degree Kelvin",
                    "Kilohertz",
                    "Megahertz",
                    "Per Hour",
                    "Milliwatts",
                    "Hectopascals",
                    "Millibars",
                    "Cubic Meters Per Hour",
                    "Liters Per Hour",
                    "Kilowatt Hours Per Square Meter",
                    "Kilowatt Hours Per Square Foot",
                    "Megajoules Per Square Meter",
                    "Megajoules Per Square Foot",
                    "Watts Per Square Meter Degree Kelvin",
                    "Cubic Feet Per Second",
                    "Percent Obscuration Per Foot",
                    "Percent Obscuration Per Meter",
                    "Milliohms",
                    "Megawatt Hours",
                    "Kilo BTUs",
                    "Mega BTUs",
                    "Kilojoules Per Kilogram Dry Air",
                    "Megajoules Per Kilogram Dry Air",
                    "Kilojoules Per Degree Kelvin",
                    "Megajoules Per Degree Kelvin",
                    "Newton",
                    "Grams Per Second",
                    "Grams Per Minute",
                    "Tons Per Hour",
                    "Kilo Btus Per Hour",
                    "Hundredths Seconds",
                    "Milliseconds",
                    "NewtonMeters",
                    "Millimeters Per Second",
                    "Millimeters Per Minute",
                    "Meters Per Minute",
                    "Meters Per Hour",
                    "Cubic Meters Per Minute",
                    "Meters Per Second Per Second",
                    "Amperes Per Meter",
                    "Amperes Per Square Meter",
                    "Ampere Square Meters",
                    "Farads",
                    "Henrys",
                    "Ohm Meters",
                    "Siemens",
                    "Siemens Per Meter",
                    "Teslas",
                    "Volts Per Degree Kelvin",
                    "Volts Per Meter",
                    "Webers",
                    "Candelas",
                    "Candelas Per Square Meter",
                    "Degrees Kelvin Per Hour",
                    "Degrees Kelvin Per Minute",
                    "Joule Seconds",
                    "Radians Per Second",
                    "Square Meters Per Newton",
                    "Kilograms Per Cubic Meter",
                    "Newton Seconds",
                    "Newtons PerMeter",
                    "Watts Per Meter Per Degree Kelvin",
                    "Volt Amperes Reactive Hours",
                    "Kilovolt Amperes Reactive Hours",
                    "Megavolt Amperes Reactive Hours",
                    "Volt Amperes Hours",
                    "Kilovolt Amperes Hours",
                    "MegaVolt Amperes Hours"

            ];


        var fieldObjectsList =
            [
                    "Access Door",
                    "Accumulator",
                    "Analog Input",
                    "Analog Output",
                    "Analog Value",
                    "Averaging",
                    "Binary Input",
                    "Binary Output",
                    "Binary Value",
                    "Calendar",
                    "Command",
                    "Device",
                    "Event Enrollment",
                    "Event Log",
                    "File",
                    "Group",
                    "Life Safety Point",
                    "Life Safety Zone",
                    "Load Control",
                    "Loop",
                    "Multi State Input",
                    "Multi State Output",
                    "Multi State Value",
                    "Notification Class",
                    "Program",
                    "Pulse Converter",
                    "Schedule",
                    "Structured View",
                    "Trend Log",
                    "Trend Log Multiple"
            ];


        var fieldPropertiesList =
            [
                    "Acked Transitions",
                    "Ack Required",
                    "Action",
                    "Action Text",
                    "Active Text",
                    "Active Vt Sessions",
                    "Alarm Value",
                    "Alarm Values",
                    "All",
                    "All Writes Successful",
                    "Apdu Segment Timeout",
                    "Apdu Timeout",
                    "Application Software Version",
                    "Archive",
                    "Bias",
                    "Change Of State Count",
                    "Change Of State Time",
                    "Notification Class",
                    "Controlled Variable Reference",
                    "Controlled Variable Units",
                    "Controlled Variable Value",
                    "Cov Increment",
                    "Date List",
                    "Daylight Savings Status",
                    "Deadband",
                    "Derivative Constant",
                    "Derivative Constant Units",
                    "Description",
                    "Description Of Halt",
                    "Device Address Binding",
                    "Device Type",
                    "Effective Period",
                    "Elapsed Active Time",
                    "Error Limit",
                    "Event Enable",
                    "Event State",
                    "Event Type",
                    "Exception Schedule",
                    "Fault Values",
                    "Feedback Value",
                    "File Access Method",
                    "File Size",
                    "File Type",
                    "Firmware Revision",
                    "High Limit",
                    "Inactive Text",
                    "In Process",
                    "Instance Of",
                    "Integral Constant",
                    "Integral Constant Units",
                    "Limit Enable",
                    "List Of Group Members",
                    "List Of Object Property References",
                    "List Of Session Keys",
                    "Local Date",
                    "Local Time",
                    "Location",
                    "Low Limit",
                    "Manipulated Variable Reference",
                    "Maximum Output",
                    "Max Apdu Length Accepted",
                    "Max Info Frames",
                    "Max Master",
                    "Max Pres Value",
                    "Minimum Off Time",
                    "Minimum On Time",
                    "Minimum Output",
                    "Min Pres Value",
                    "Model Name",
                    "Modification Date" ,
                    "Notify Type",
                    "Number Of Apdu Retries",
                    "Number Of States" ,
                    "Object Identifier",
                    "Object List",
                    "Object Name",
                    "Object Property Reference",
                    "Object Type",
                    "Optional",
                    "Out Of Service",
                    "Output Units",
                    "Event Parameters" ,
                    "Polarity",
                    "Present Value",
                    "Priority",
                    "Priority Array",
                    "Priority For Writing",
                    "Process Identifier",
                    "Program Change",
                    "Program Location",
                    "Program State" ,
                    "Proportional Constant" ,
                    "Proportional Constant Units" ,
                    "Protocol Object Types Supported" ,
                    "Protocol Services Supported" ,
                    "Protocol Version" ,
                    "Read Only",
                    "Reason For Halt",
                    "Recipient List",
                    "Reliability",
                    "Relinquish Default",
                    "Required",
                    "Resolution" ,
                    "Segmentation Supported" ,
                    "Setpoint" ,
                    "Setpoint Reference" ,
                    "State Text" ,
                    "Status Flags" ,
                    "System Status" ,
                    "Time Delay" ,
                    "Time Of Active Time Reset" ,
                    "Time Of State Count Reset",
                    "Time Synchronization Recipients" ,
                    "Units" ,
                    "Update Interval" ,
                    "Utc Offset" ,
                    "Vendor Identifier" ,
                    "Vendor Name" ,
                    "Vt Classes Supported" ,
                    "Weekly Schedule" ,
                    "Attempted Samples" ,
                    "Average Value" ,
                    "Buffer Size" ,
                    "Client Cov Increment" ,
                    "Cov Resubscription Interval" ,
                    "Event Time Stamps" ,
                    "Log Buffer" ,
                    "Log Device Object Property" ,
                    "Enable",
                    "Log Interval" ,
                    "Maximum Value" ,
                    "Minimum Value",
                    "Notification Threshold",
                    "Protocol Revision" ,
                    "Records Since Notification",
                    "Record Count" ,
                    "Start Time" ,
                    "Stop Time",
                    "Stop When Full",
                    "Total Record Count",
                    "Valid Samples",
                    "Window Interval",
                    "Window Samples",
                    "Maximum Value Timestamp",
                    "Minimum Value Timestamp",
                    "Variance Value",
                    "Active Cov Subscriptions",
                    "Backup Failure Timeout",
                    "Configuration Files",
                    "Database Revision",
                    "Direct Reading",
                    "Last Restore Time",
                    "Maintenance Required",
                    "Member Of",
                    "Mode",
                    "Operation Expected",
                    "Setting",
                    "Silenced",
                    "Tracking Value",
                    "Zone Members",
                    "Life Safety Alarm Values",
                    "Max Segments Accepted",
                    "Profile Name",
                    "Auto Slave Discovery",
                    "Manual Slave Address Binding",
                    "Slave Address Binding",
                    "Slave Proxy Enable",
                    "Last Notify Record",
                    "Schedule Default",
                    "Accepted Modes",
                    "Adjust Value",
                    "Count",
                    "Count Before Change",
                    "Count Change Time",
                    "Cov Period",
                    "Input Reference" ,
                    "Limit Monitoring Interval" ,
                    "Logging Object",
                    "Logging Record" ,
                    "Prescale",
                    "Pulse Rate",
                    "Scale",
                    "Scale Factor",
                    "Update Time",
                    "Value Before Change",
                    "Value Set",
                    "Value Change Time",
                    "Align Intervals",
                    "Interval Offset",
                    "Last Restart Reason",
                    "Logging Type",
                    "Restart Notification Recipients",
                    "Time Of Device Restart",
                    "Time Synchronization Interval",
                    "Trigger",
                    "Utc Time Synchronization Recipients" ,
                    "Node Subtype",
                    "Node Type" ,
                    "Structured Object List" ,
                    "Subordinate Annotations",
                    "Subordinate List" ,
                    "Actual Shed Level" ,
                    "Duty Window",
                    "Expected Shed Level" ,
                    "Full Duty Baseline" ,
                    "Requested Shed Level" ,
                    "Shed Duration" ,
                    "Shed Level Descriptions" ,
                    "Shed Levels",
                    "State Description",
                    "Door Alarm State",
                    "Door Extended Pulse Time",
                    "Door Members",
                    "Door Open Too Long Time",
                    "Door Pulse Time" ,
                    "Door Status" ,
                    "Door Unlock Delay Time" ,
                    "Lock Status" ,
                    "Masked Alarm Values",
                    "Secured Status" ,
                    "Backup And Restore State" ,
                    "Backup Preparation Time" ,
                    "Restore Completion Time" ,
                    "Restore Preparation Time"
            ];

        return {

                engineeringUnitList: engineeringUnitList,
                fieldObjectsList: fieldObjectsList,
                fieldPropertiesList: fieldPropertiesList,
                fontList:fontList,
                typeSort: typeSort,
                selectType: selectType,
                objectTypes: objectTypes,
                propertyList: PropertyList

        };

}





